// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'reference-for-zotero-section-header'
  | 'reference-for-zotero-section-settings'
  | 'reference-for-zotero-section-sidenav';
